---
- name: Playbook downloading and extracting Hadoop
  hosts: nameNode
  gather_facts: no

  vars:
    tar_dest: "/home/hadoop"
    hadoop_version: "hadoop-3.3.0-aarch64"
  
  
  tasks:
    
    - name: Download Hadoop from Apache site
    # check if it can be done without become
      become: yes
      get_url:
        
        url: https://apache.mirrors.tworzy.net/hadoop/common/hadoop-3.3.0/{{ hadoop_version }}.tar.gz
        checksum: "sha512:8322868e255e3d84a2e796cc7728cdae2d06b3fdf26e1034eaeab91341ecafe7ce58a238f9fd0aceb4c905c80230fe3267fbe53ebaa0a78ec44a0d1f9df64006"
        dest: "{{ tar_dest }}/{{ hadoop_version }}.tar.gz"
        force: yes
        mode: 0666
                

    - name: Extract the hadoop tarball
      become: yes
      unarchive:
        src: "{{ tar_dest }}/{{ hadoop_version }}.tar.gz"
        dest: /usr/local/
        creates: /usr/local/{{hadoop_version}}
        remote_src: yes
        group: hadoop
        owner: hadoop
        